title: Artamoshkin Maxim · Blog
# Site settings
email: admin@zverit.com
description: > # this means to ignore newlines until "baseurl:"
  Добро пожаловать на блог fullstack-разработчика. 
  </br>
  Здесь я пишу в основном о веб-разработке, в частности
  о ASP.NET, С<span>#</span>, JavaScript, Angular. 
  </br>А также об околокодинговых темах. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.zverit.com" # the base hostname & protocol for your site
twitter_username: zverit 
github_username:  Zverit

permalink: pretty
 
safe: true

paginate: 6

gems: 
  - jekyll-sitemap 
  - jekyll-feed
  
# Build settings
markdown: kramdown

url: https://blog.zverit.com   # with the https protocol
enforce_ssl: blog.zverit.com   # without any protocol

jekyll-archives:
  enabled:
  - year
  - month
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
